//import { createClient } from "@/lib/supabase/server"
import { createServerClient } from "@/lib/supabase/server"
import { format, subDays, isBefore, addDays } from "date-fns"
import { es, enUS, pt } from "date-fns/locale"
import { Resend } from "resend"

export class WeeklyReportServiceV8 {
  private static resend = new Resend(process.env.RESEND_API_KEY)

  // Traducciones hardcodeadas
  private static translations = {
    es: {
      weeklyReport: "Reporte Semanal",
      generatedOn: "Generado el",
      summary: "Resumen",
      active: "ACTIVAS",
      new: "NUEVAS",
      won: "GANADAS",
      lost: "PERDIDAS",
      withActivity: "CON ACTIVIDAD",
      withoutActivity: "SIN ACTIVIDAD",
      thisWeek: "Esta semana",
      opportunitiesByPartner: "Oportunidades por Partner",
      newThisWeek: "Nuevas esta semana",
      inProgress: "En progreso",
      wonThisWeek: "Ganadas esta semana",
      lostThisWeek: "Perdidas esta semana",
      country: "País",
      opportunity: "Oportunidad",
      endCustomer: "Cliente Final",
      amount: "Monto",
      estimatedClose: "Cierre Estimado",
      lastActivity: "Última Actividad",
      noOpportunities: "No hay oportunidades en esta categoría.",
      noActivityThisWeek: "Sin actividad esta semana",
      overdue: "Vencida",
      dueIn7Days: "Vence en 7 días",
      opportunityUpdated: "Oportunidad actualizada",
      newNoteAdded: "Nueva nota agregada",
      task: "Tarea",
      newTask: "Nueva tarea",
      autoGenerated: "Este reporte fue generado automáticamente por",
      activityNote: "Incluye cambios de estado, creación de tareas o notas en la última semana.",
      frozenLostNote: "Las oportunidades congeladas o perdidas solo se muestran la semana que cambiaron a ese estado.",
      withoutPartner: "Sin Partner",
    },
    en: {
      weeklyReport: "Weekly Report",
      generatedOn: "Generated on",
      summary: "Summary",
      active: "ACTIVE",
      new: "NEW",
      won: "WON",
      lost: "LOST",
      withActivity: "WITH ACTIVITY",
      withoutActivity: "WITHOUT ACTIVITY",
      thisWeek: "This week",
      opportunitiesByPartner: "Opportunities by Partner",
      newThisWeek: "New this week",
      inProgress: "In progress",
      wonThisWeek: "Won this week",
      lostThisWeek: "Lost this week",
      country: "Country",
      opportunity: "Opportunity",
      endCustomer: "End Customer",
      amount: "Amount",
      estimatedClose: "Estimated Close",
      lastActivity: "Last Activity",
      noOpportunities: "No opportunities in this category.",
      noActivityThisWeek: "No activity this week",
      overdue: "Overdue",
      dueIn7Days: "Due in 7 days",
      opportunityUpdated: "Opportunity updated",
      newNoteAdded: "New note added",
      task: "Task",
      newTask: "New task",
      autoGenerated: "This report was automatically generated by",
      activityNote: "Includes status changes, task or note creation in the last week.",
      frozenLostNote: "Frozen or lost opportunities are only shown the week they changed to that status.",
      withoutPartner: "Without Partner",
    },
    pt: {
      weeklyReport: "Relatório Semanal",
      generatedOn: "Gerado em",
      summary: "Resumo",
      active: "ATIVAS",
      new: "NOVAS",
      won: "GANHAS",
      lost: "PERDIDAS",
      withActivity: "COM ATIVIDADE",
      withoutActivity: "SEM ATIVIDADE",
      thisWeek: "Esta semana",
      opportunitiesByPartner: "Oportunidades por Parceiro",
      newThisWeek: "Novas esta semana",
      inProgress: "Em progresso",
      wonThisWeek: "Ganhas esta semana",
      lostThisWeek: "Perdidas esta semana",
      country: "País",
      opportunity: "Oportunidade",
      endCustomer: "Cliente Final",
      amount: "Valor",
      estimatedClose: "Fechamento Estimado",
      lastActivity: "Última Atividade",
      noOpportunities: "Não há oportunidades nesta categoria.",
      noActivityThisWeek: "Sem atividade esta semana",
      overdue: "Vencida",
      dueIn7Days: "Vence em 7 dias",
      opportunityUpdated: "Oportunidade atualizada",
      newNoteAdded: "Nova nota adicionada",
      task: "Tarefa",
      newTask: "Nova tarefa",
      autoGenerated: "Este relatório foi gerado automaticamente pelo",
      activityNote: "Inclui mudanças de status, criação de tarefas ou notas na última semana.",
      frozenLostNote: "Oportunidades congeladas ou perdidas só são mostradas na semana que mudaram para esse status.",
      withoutPartner: "Sem Parceiro",
    },
  }

  static async sendWeeklyReport(techCompanyId: string, supabaseClient?: any) {
    console.log(`[WeeklyReportServiceV8] === INICIO sendWeeklyReport para ${techCompanyId} ===`)

    try {
      const supabase = createServerClient()

      // 1. Obtener tech company
      console.log(`[WeeklyReportServiceV8] 1. Obteniendo tech company...`)
      const techCompanyResponse = await supabase
        .from("tech_companies")
        .select("id, name, logo_url")
        .eq("id", techCompanyId)
        .single()

      const { data: techCompany, error: techError } = techCompanyResponse

      if (techError || !techCompany) {
        console.error(`[WeeklyReportServiceV8] Error tech company:`, techError)
        return { success: false, results: [], error: "Tech company not found" }
      }
      console.log(`[WeeklyReportServiceV8] Tech company OK:`, techCompany.name)

      // 2. Obtener destinatarios CON IDIOMA
      console.log(`[WeeklyReportServiceV8] 2. Obteniendo destinatarios...`)
      const { data: recipientData, error: recipientError } = await supabase
        .from("weekly_report_recipients")
        .select(`
          user_id,
          preferred_language,
          users (
            id,
            email,
            first_name,
            last_name,
            preferred_language
          )
        `)
        .eq("tech_company_id", techCompanyId)
        .eq("is_active", true)

      if (recipientError) {
        console.error(`[WeeklyReportServiceV8] Error recipients:`, recipientError)
        return { success: false, results: [], error: "Error getting recipients" }
      }

      if (!recipientData || recipientData.length === 0) {
        console.log(`[WeeklyReportServiceV8] No recipients found`)
        return { success: false, results: [], error: "No recipients configured" }
      }

      console.log(`[WeeklyReportServiceV8] Found ${recipientData.length} recipients`)

      // 3. Verificar configuración de email
      if (!process.env.RESEND_API_KEY) {
        console.error(`[WeeklyReportServiceV8] RESEND_API_KEY not configured`)
        return { success: false, results: [], error: "RESEND_API_KEY not configured" }
      }

      // 4. Obtener oportunidades SOLO de partners activos o sin partner
      console.log(`[WeeklyReportServiceV8] 3. Obteniendo oportunidades (solo partners activos)...`)

      const oneWeekAgo = subDays(new Date(), 7)

      // PRIMERA CONSULTA: Oportunidades SIN partner asignado
      const { data: opportunitiesWithoutPartner, error: oppWithoutPartnerError } = await supabase
        .from("opportunities")
        .select(`
          id, 
          title, 
          estimated_value, 
          estimated_close_date, 
          created_at, 
          updated_at,
          country,
          partner_id,
          pipeline_stages (code),
          end_customers (name)
        `)
        .eq("tech_company_id", techCompanyId)
        .is("partner_id", null)
        .order("created_at", { ascending: false })

      if (oppWithoutPartnerError) {
        console.error(`[WeeklyReportServiceV8] Error opportunities without partner:`, oppWithoutPartnerError)
        return {
          success: false,
          results: [],
          error: `Error getting opportunities without partner: ${oppWithoutPartnerError.message}`,
        }
      }

      // SEGUNDA CONSULTA: Oportunidades CON partner activo
      const { data: opportunitiesWithActivePartner, error: oppWithActivePartnerError } = await supabase
        .from("opportunities")
        .select(`
          id, 
          title, 
          estimated_value, 
          estimated_close_date, 
          created_at, 
          updated_at,
          country,
          partner_id,
          pipeline_stages (code),
          partners!inner (name, logo_url, is_active),
          end_customers (name)
        `)
        .eq("tech_company_id", techCompanyId)
        .eq("partners.is_active", true)
        .order("created_at", { ascending: false })

      if (oppWithActivePartnerError) {
        console.error(`[WeeklyReportServiceV8] Error opportunities with active partner:`, oppWithActivePartnerError)
        return {
          success: false,
          results: [],
          error: `Error getting opportunities with active partner: ${oppWithActivePartnerError.message}`,
        }
      }

      // Combinar ambos resultados
      const opportunitiesWithoutPartnerFormatted = (opportunitiesWithoutPartner || []).map((opp) => ({
        ...opp,
        partners: null,
      }))

      const opportunitiesWithActivePartnerFormatted = (opportunitiesWithActivePartner || []).map((opp) => ({
        ...opp,
        partners: {
          name: opp.partners?.name,
          logo_url: opp.partners?.logo_url,
        },
      }))

      const allOpportunities = [...opportunitiesWithoutPartnerFormatted, ...opportunitiesWithActivePartnerFormatted]

      console.log(
        `[WeeklyReportServiceV8] Found ${allOpportunities.length} opportunities (${opportunitiesWithoutPartnerFormatted.length} sin partner, ${opportunitiesWithActivePartnerFormatted.length} con partner activo)`,
      )

      // 5. Obtener campos técnicos
      console.log(`[WeeklyReportServiceV8] 4. Obteniendo campos técnicos...`)
      const opportunityIds = allOpportunities.map((opp) => opp.id)
      const techFieldsByOpportunity: { [key: string]: any[] } = {}

      if (opportunityIds.length > 0) {
        console.log(`[WeeklyReportServiceV8] Buscando campos técnicos para ${opportunityIds.length} oportunidades`)

        // PASO 1: Obtener campos técnicos
        const { data: allTechFields, error: fieldsError } = await supabase
          .from("opportunity_tech_fields")
          .select("id, field_name, field_type, tech_company_id")
          .eq("tech_company_id", techCompanyId)

        console.log(`[WeeklyReportServiceV8] 📋 Campos técnicos disponibles:`, allTechFields?.length || 0)

        // PASO 2: Obtener valores técnicos
        const { data: allTechValues, error: valuesError } = await supabase
          .from("opportunity_tech_values")
          .select(
            "id, opportunity_id, opportunity_tech_field_id, value_text, value_numeric, value_boolean, value_date, value_json",
          )
          .in("opportunity_id", opportunityIds)

        console.log(`[WeeklyReportServiceV8] 📊 Valores técnicos disponibles:`, allTechValues?.length || 0)

        // PASO 3: Hacer JOIN manual
        if (allTechFields && allTechValues && allTechFields.length > 0 && allTechValues.length > 0) {
          console.log(`[WeeklyReportServiceV8] 🔗 Haciendo JOIN manual...`)

          // Crear mapa de campos por ID para lookup rápido
          const fieldsById: { [key: string]: any } = {}
          allTechFields.forEach((field) => {
            fieldsById[field.id] = field
          })

          // Procesar cada valor y hacer el JOIN
          allTechValues.forEach((value) => {
            const field = fieldsById[value.opportunity_tech_field_id]

            // Determinar el valor real según el tipo
            let actualValue = null
            if (value.value_text) actualValue = value.value_text
            else if (value.value_numeric !== null) actualValue = value.value_numeric
            else if (value.value_boolean !== null) actualValue = value.value_boolean ? "Sí" : "No"
            else if (value.value_date) actualValue = value.value_date
            else if (value.value_json) actualValue = JSON.stringify(value.value_json)

            if (field && value.opportunity_id && actualValue !== null) {
              const oppId = value.opportunity_id

              if (!techFieldsByOpportunity[oppId]) {
                techFieldsByOpportunity[oppId] = []
              }

              techFieldsByOpportunity[oppId].push({
                name: field.field_name,
                value: actualValue,
                type: field.field_type || "text",
              })
            }
          })

          console.log(
            `[WeeklyReportServiceV8] 🎯 RESUMEN FINAL: Campos técnicos organizados para ${Object.keys(techFieldsByOpportunity).length} oportunidades`,
          )
        }
      }

      // 6. Obtener actividad detallada por oportunidad
      console.log(`[WeeklyReportServiceV8] 5. Obteniendo actividad por oportunidad...`)
      const activityByOpportunity: { [key: string]: { lastActivity: Date | null; description: string } } = {}

      if (opportunityIds.length > 0) {
        // Obtener tareas recientes
        const { data: recentTasks } = await supabase
          .from("tasks")
          .select("opportunity_id, created_at, updated_at, title")
          .in("opportunity_id", opportunityIds)
          .gte("created_at", oneWeekAgo.toISOString())
          .order("created_at", { ascending: false })

        // Obtener notas recientes
        const { data: recentNotes } = await supabase
          .from("notes")
          .select("opportunity_id, created_at, updated_at")
          .in("opportunity_id", opportunityIds)
          .gte("created_at", oneWeekAgo.toISOString())
          .order("created_at", { ascending: false })

        // Procesar actividad por oportunidad
        allOpportunities.forEach((opp) => {
          const oppTasks = recentTasks?.filter((task) => task.opportunity_id === opp.id) || []
          const oppNotes = recentNotes?.filter((note) => note.opportunity_id === opp.id) || []

          let lastActivity: Date | null = null
          let description = "Sin actividad esta semana"

          // Verificar actualización de la oportunidad misma
          if (opp.updated_at && new Date(opp.updated_at) >= oneWeekAgo) {
            lastActivity = new Date(opp.updated_at)
            description = "Oportunidad actualizada"
          }

          // Verificar tareas más recientes
          if (oppTasks.length > 0) {
            const latestTask = oppTasks[0]
            const taskDate = new Date(latestTask.created_at)
            if (!lastActivity || taskDate > lastActivity) {
              lastActivity = taskDate
              description = `Tarea: ${latestTask.title?.substring(0, 30) || "Nueva tarea"}${latestTask.title && latestTask.title.length > 30 ? "..." : ""}`
            }
          }

          // Verificar notas más recientes
          if (oppNotes.length > 0) {
            const latestNote = oppNotes[0]
            const noteDate = new Date(latestNote.created_at)
            if (!lastActivity || noteDate > lastActivity) {
              lastActivity = noteDate
              description = "Nueva nota agregada"
            }
          }

          activityByOpportunity[opp.id] = {
            lastActivity,
            description,
          }
        })
      }

      // 7. Obtener actividad de la semana para contadores
      const { data: weeklyTasks } = await supabase
        .from("tasks")
        .select("opportunity_id")
        .eq("tech_company_id", techCompanyId)
        .gte("created_at", oneWeekAgo.toISOString())

      const { data: weeklyNotes } = await supabase
        .from("notes")
        .select("opportunity_id")
        .gte("created_at", oneWeekAgo.toISOString())

      const opportunitiesWithActivity = new Set([
        ...(weeklyTasks || []).map((t) => t.opportunity_id),
        ...(weeklyNotes || []).map((n) => n.opportunity_id),
        ...allOpportunities
          .filter((opp) => opp.updated_at && new Date(opp.updated_at) >= oneWeekAgo)
          .map((opp) => opp.id),
      ])

      // 8. Clasificar oportunidades
      const inactiveStages = ["Freeze", "Lost"]

      // Separar oportunidades activas de inactivas (aquí sí podemos mantener Won como "no activa" para el conteo principal)
const activeOpportunities = allOpportunities.filter(
  (opp) => !["Freeze", "Lost", "Won"].includes(opp.pipeline_stages?.code || ""),
)

      // Oportunidades que se movieron a Freeze/Lost esta semana
      const recentlyInactiveOpportunities = allOpportunities.filter((opp) => {
        const isInactive = inactiveStages.includes(opp.pipeline_stages?.code || "")
        const wasUpdatedThisWeek = opp.updated_at && new Date(opp.updated_at) >= oneWeekAgo
        return isInactive && wasUpdatedThisWeek
      })

      // Clasificar solo las oportunidades activas
      const newOpportunities = activeOpportunities.filter((opp) => new Date(opp.created_at) >= oneWeekAgo)
      const existingOpportunities = activeOpportunities.filter((opp) => new Date(opp.created_at) < oneWeekAgo)

      // Oportunidades ganadas esta semana
      const wonThisWeek = allOpportunities.filter((opp) => {
        const isWon = opp.pipeline_stages?.code === "Won"
        const wasUpdatedThisWeek = opp.updated_at && new Date(opp.updated_at) >= oneWeekAgo
        return isWon && wasUpdatedThisWeek
      })

      const withActivity = activeOpportunities.filter((opp) => opportunitiesWithActivity.has(opp.id)).length
      const withoutActivity = activeOpportunities.length - withActivity

      // 9. Agrupar por Partner
      const groupByPartner = (opportunities: any[]) => {
        const grouped: { [key: string]: any[] } = {}

        opportunities.forEach((opp) => {
          const partnerName = opp.partners?.name || "Sin Partner"
          if (!grouped[partnerName]) {
            grouped[partnerName] = []
          }

          // Agregar campos técnicos y actividad a la oportunidad
          opp.techFields = techFieldsByOpportunity[opp.id] || []
          opp.lastActivity = activityByOpportunity[opp.id] || {
            lastActivity: null,
            description: "Sin actividad esta semana",
          }

          grouped[partnerName].push(opp)
        })

        return grouped
      }

      const newByPartner = groupByPartner(newOpportunities)
      const existingByPartner = groupByPartner(existingOpportunities)
      const wonByPartner = groupByPartner(wonThisWeek)
      const inactiveByPartner = groupByPartner(recentlyInactiveOpportunities)

      // 10. Obtener información de partners únicos para logos
      const allPartnerNames = new Set([
        ...Object.keys(newByPartner),
        ...Object.keys(existingByPartner),
        ...Object.keys(wonByPartner),
        ...Object.keys(inactiveByPartner),
      ])

      // Obtener logos de partners
      const partnerLogos: { [key: string]: string } = {}
      if (allPartnerNames.size > 0) {
        const partnerNamesArray = Array.from(allPartnerNames).filter((name) => name !== "Sin Partner")
        if (partnerNamesArray.length > 0) {
          const { data: partnersData } = await supabase
            .from("partners")
            .select("name, logo_url")
            .in("name", partnerNamesArray)
            .eq("is_active", true)

          if (partnersData) {
            partnersData.forEach((partner) => {
              if (partner.logo_url) {
                partnerLogos[partner.name] = partner.logo_url
              }
            })
          }
        }
      }

      // 11. Calcular valores totales
      const calculateTotalValue = (opportunities: any[]) => {
        return opportunities.reduce((total, opp) => total + (opp.estimated_value || 0), 0)
      }

      const totalActiveValue = calculateTotalValue(activeOpportunities)
      const totalNewValue = calculateTotalValue(newOpportunities)
      const totalWonValue = calculateTotalValue(wonThisWeek)

      // 12. Generar datos del reporte
      const reportData = {
        techCompany,
        partnerLogos,
        summary: {
          totalActiveOpportunities: activeOpportunities.length,
          newThisWeek: newOpportunities.length,
          wonThisWeek: wonThisWeek.length,
          inactiveThisWeek: recentlyInactiveOpportunities.length,
          withActivity,
          withoutActivity,
          totalActiveValue,
          totalNewValue,
          totalWonValue,
        },
        opportunitiesByPartner: {
          new: newByPartner,
          existing: existingByPartner,
          won: wonByPartner,
          inactive: inactiveByPartner,
        },
        generatedAt: new Date(),
        techFieldsByOpportunity,
        activityByOpportunity,
      }

      // 13. Enviar emails a cada destinatario en su idioma
      console.log(`[WeeklyReportServiceV8] 6. Enviando emails...`)
      const results = []
      const emailFrom = process.env.NEXT_PUBLIC_EMAIL_FROM || "ScaleUp CRM <no-reply@scaleup-global.com>"

      for (const recipient of recipientData) {
        try {
          // Determinar idioma: primero el del recipient, luego el del usuario, por defecto español
          const userLanguage = recipient.preferred_language || recipient.users.preferred_language || "es"
          const language = ["es", "en", "pt"].includes(userLanguage) ? userLanguage : "es"

          console.log(`[WeeklyReportServiceV8] Enviando a ${recipient.users.email} en idioma: ${language}`)

          // Generar HTML en el idioma correspondiente
          const htmlContent = this.generateUltraCompactHtml(reportData, language)

          // Generar subject con fecha en el idioma correspondiente
          const reportDate = format(new Date(), "dd/MM/yyyy")
          const t = this.translations[language as keyof typeof this.translations]
          const emailSubject = `${techCompany.name} - ${t.weeklyReport} ${reportDate} (${reportData.summary.totalActiveOpportunities} ${t.active.toLowerCase()})`

          const { data, error } = await this.resend.emails.send({
            from: emailFrom,
            to: [recipient.users.email],
            subject: emailSubject,
            html: htmlContent,
          })

          if (error) {
            console.error(`[WeeklyReportServiceV8] Error enviando a ${recipient.users.email}:`, error)
            results.push({
              email: recipient.users.email,
              success: false,
              message: error.message,
            })
          } else {
            console.log(`[WeeklyReportServiceV8] Email enviado exitosamente a ${recipient.users.email}`)
            results.push({
              email: recipient.users.email,
              success: true,
              message: "Email sent successfully",
            })
          }

          // Pausa entre emails
          await new Promise((resolve) => setTimeout(resolve, 1000))
        } catch (error) {
          console.error(`[WeeklyReportServiceV8] Error inesperado enviando a ${recipient.users.email}:`, error)
          results.push({
            email: recipient.users.email,
            success: false,
            message: error instanceof Error ? error.message : "Unknown error",
          })
        }
      }

      const successCount = results.filter((r) => r.success).length
      console.log(`[WeeklyReportServiceV8] Completado: ${successCount}/${results.length} emails enviados`)

      return {
        success: successCount > 0,
        results,
        summary: reportData.summary,
      }
    } catch (error) {
      console.error(`[WeeklyReportServiceV8] Error general:`, error)
      return {
        success: false,
        results: [],
        error: error instanceof Error ? error.message : "Unknown error",
      }
    }
  }

  private static generateUltraCompactHtml(reportData: any, language = "es"): string {
    const { techCompany, partnerLogos, summary, opportunitiesByPartner, generatedAt } = reportData
    const scaleupBlue = "#0055b8"

    // Obtener traducciones para el idioma
    const t = this.translations[language as keyof typeof this.translations] || this.translations.es

    // Seleccionar locale para fechas
    const getLocale = () => {
      switch (language) {
        case "en":
          return enUS
        case "pt":
          return pt
        case "es":
        default:
          return es
      }
    }

    const locale = getLocale()
    const formattedDate = format(generatedAt, "PPP", { locale })

    const formatCurrency = (amount?: number) => {
      if (!amount) return "-"
      return new Intl.NumberFormat("es-ES", {
        style: "currency",
        currency: "USD",
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(amount)
    }

    // Función para determinar el color de fondo según la fecha de cierre
    const getRowBackgroundColor = (estimatedCloseDate?: string) => {
      if (!estimatedCloseDate) return "white"

      const closeDate = new Date(estimatedCloseDate)
      const today = new Date()
      const sevenDaysFromNow = addDays(today, 7)

      // Si la fecha ya pasó (vencida)
      if (isBefore(closeDate, today)) {
        return "#ffebee" // Rojo suave
      }

      // Si vence en los próximos 7 días
      if (isBefore(closeDate, sevenDaysFromNow)) {
        return "#fff8e1" // Amarillo suave
      }

      return "white"
    }

    // Función para formatear campos técnicos
    const formatTechFields = (techFields: any[]) => {
      if (!techFields || techFields.length === 0) {
        return ""
      }

      // Filtrar campos válidos y formatear
      const validFields = techFields.filter((field) => {
        return field && field.name && field.value && field.name.trim() !== "" && field.value.toString().trim() !== ""
      })

      if (validFields.length === 0) {
        return ""
      }

      const formattedFields = validFields
        .map((field) => {
          let displayValue = field.value
          if (field.type === "boolean") {
            displayValue = field.value === "true" || field.value === true ? "Sí" : "No"
          }
          return `<strong>${field.name}:</strong> ${displayValue}`
        })
        .join("<br>")

      return `<div style="font-size: 11px; color: #666; margin-top: 6px; font-style: italic; line-height: 1.4; padding: 6px 10px; background-color: #f0f8ff; border-radius: 4px; border-left: 3px solid #007bff;">${formattedFields}</div>`
    }

    // Función para formatear última actividad
    const formatLastActivity = (lastActivity: any) => {
      if (!lastActivity || !lastActivity.lastActivity) {
        return `<span style="color: #dc3545; font-size: 10px;">${t.noActivityThisWeek}</span>`
      }

      const activityDate = format(new Date(lastActivity.lastActivity), "dd/MM")

      // Traducir descripción de actividad
      let translatedDescription = lastActivity.description
      if (lastActivity.description === "Oportunidad actualizada") {
        translatedDescription = t.opportunityUpdated
      } else if (lastActivity.description === "Nueva nota agregada") {
        translatedDescription = t.newNoteAdded
      } else if (lastActivity.description.startsWith("Tarea:")) {
        const taskTitle = lastActivity.description.replace("Tarea: ", "")
        translatedDescription = `${t.task}: ${taskTitle}`
      }

      return `<div style="font-size: 10px; color: #28a745;">
        <div style="font-weight: 600;">${activityDate}</div>
        <div style="color: #666; margin-top: 2px;">${translatedDescription}</div>
      </div>`
    }

    const generateOpportunityTable = (opps: any[], showEndCustomer = true) => {
      if (!opps || opps.length === 0) {
        return `<p style="color: #666; font-style: italic; text-align: center; padding: 20px;">${t.noOpportunities}</p>`
      }

      const rows = opps
        .map((opp) => {
          const backgroundColor = getRowBackgroundColor(opp.estimated_close_date)

          return `
        <tr style="border-bottom: 1px solid #e0e0e0; background-color: ${backgroundColor};">
          <td style="padding: 12px; border-right: 1px solid #e0e0e0; width: 70px; text-align: center;">${opp.country || "-"}</td>
          <td style="padding: 12px; border-right: 1px solid #e0e0e0; width: 280px; font-weight: 500;">
            <div style="font-weight: 600; color: #333; margin-bottom: 4px;">${opp.title}</div>
            ${formatTechFields(opp.techFields)}
          </td>
          ${showEndCustomer ? `<td style="padding: 12px; border-right: 1px solid #e0e0e0; width: 160px;">${opp.end_customers?.name || "-"}</td>` : ""}
          <td style="padding: 12px; border-right: 1px solid #e0e0e0; width: 100px; text-align: right; font-weight: 600; color: ${scaleupBlue};">${formatCurrency(opp.estimated_value)}</td>
          <td style="padding: 12px; border-right: 1px solid #e0e0e0; width: 90px; text-align: center;">${opp.estimated_close_date ? format(new Date(opp.estimated_close_date), "dd/MM/yyyy") : "-"}</td>
          <td style="padding: 12px; width: 120px; text-align: center;">${formatLastActivity(opp.lastActivity)}</td>
        </tr>
      `
        })
        .join("")

      return `
        <table style="width: 100%; border-collapse: collapse; border: 1px solid #e0e0e0; background-color: white; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
          <thead>
            <tr style="background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);">
              <th style="padding: 15px; text-align: center; border-right: 1px solid #e0e0e0; font-size: 13px; font-weight: 600; color: #495057; width: 70px;">${t.country}</th>
              <th style="padding: 15px; text-align: left; border-right: 1px solid #e0e0e0; font-size: 13px; font-weight: 600; color: #495057; width: 280px;">${t.opportunity}</th>
              ${showEndCustomer ? `<th style="padding: 15px; text-align: left; border-right: 1px solid #e0e0e0; font-size: 13px; font-weight: 600; color: #495057; width: 160px;">${t.endCustomer}</th>` : ""}
              <th style="padding: 15px; text-align: center; border-right: 1px solid #e0e0e0; font-size: 13px; font-weight: 600; color: #495057; width: 100px;">${t.amount}</th>
              <th style="padding: 15px; text-align: center; border-right: 1px solid #e0e0e0; font-size: 13px; font-weight: 600; color: #495057; width: 90px;">${t.estimatedClose}</th>
              <th style="padding: 15px; text-align: center; font-size: 13px; font-weight: 600; color: #495057; width: 120px;">${t.lastActivity}</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>
      `
    }

    const generatePartnerSection = (partnerName: string, partnerData: any) => {
      const hasData =
        (partnerData.new && partnerData.new.length > 0) ||
        (partnerData.existing && partnerData.existing.length > 0) ||
        (partnerData.won && partnerData.won.length > 0) ||
        (partnerData.inactive && partnerData.inactive.length > 0)

      if (!hasData) return ""

      // Traducir nombre del partner si es "Sin Partner"
      const translatedPartnerName = partnerName === "Sin Partner" ? t.withoutPartner : partnerName

      // Obtener logo del partner con dimensiones proporcionales
      const partnerLogo = partnerLogos[partnerName]
      const partnerIcon = partnerLogo
        ? `<img src="${partnerLogo}" alt="${translatedPartnerName}" style="height: 32px; width: auto; max-width: 120px; border-radius: 6px; object-fit: contain; margin-right: 12px; background-color: white; padding: 4px;">`
        : partnerName === "Sin Partner"
          ? `<span style="font-size: 24px; margin-right: 12px;">🏢</span>`
          : `<span style="font-size: 24px; margin-right: 12px;">🤝</span>`

      return `
        <div style="margin: 30px 0; border: 2px solid ${scaleupBlue}; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          <div style="background: linear-gradient(135deg, ${scaleupBlue} 0%, #003d82 100%); color: white; padding: 20px; display: flex; align-items: center;">
            ${partnerIcon}
            <h2 style="margin: 0; font-size: 20px; font-weight: 600;">${translatedPartnerName}</h2>
          </div>
          <div style="padding: 25px; background-color: #fafbfc;">
            ${
              partnerData.new && partnerData.new.length > 0
                ? `
              <div style="margin-bottom: 25px;">
                <h3 style="color: ${scaleupBlue}; margin-bottom: 15px; font-size: 16px; font-weight: 600; display: flex; align-items: center;">
                  <span style="font-size: 20px; margin-right: 8px;">🆕</span>
                  ${t.newThisWeek} (${partnerData.new.length})
                </h3>
                ${generateOpportunityTable(partnerData.new)}
              </div>
            `
                : ""
            }
            
            ${
              partnerData.existing && partnerData.existing.length > 0
                ? `
              <div style="margin-bottom: 25px;">
                <h3 style="color: ${scaleupBlue}; margin-bottom: 15px; font-size: 16px; font-weight: 600; display: flex; align-items: center;">
                  <span style="font-size: 20px; margin-right: 8px;">📋</span>
                  ${t.inProgress} (${partnerData.existing.length})
                </h3>
                ${generateOpportunityTable(partnerData.existing)}
              </div>
            `
                : ""
            }
            
            ${
              partnerData.won && partnerData.won.length > 0
                ? `
              <div style="margin-bottom: 25px;">
                <h3 style="color: #28a745; margin-bottom: 15px; font-size: 16px; font-weight: 600; display: flex; align-items: center;">
                  <span style="font-size: 20px; margin-right: 8px;">🏆</span>
                  ${t.wonThisWeek} (${partnerData.won.length})
                </h3>
                ${generateOpportunityTable(partnerData.won)}
              </div>
            `
                : ""
            }
            
            ${
              partnerData.inactive && partnerData.inactive.length > 0
                ? `
              <div style="margin-bottom: 25px;">
                <h3 style="color: #dc3545; margin-bottom: 15px; font-size: 16px; font-weight: 600; display: flex; align-items: center;">
                  <span style="font-size: 20px; margin-right: 8px;">❄️</span>
                  ${t.lostThisWeek} (${partnerData.inactive.length})
                </h3>
                ${generateOpportunityTable(partnerData.inactive)}
              </div>
            `
                : ""
            }
          </div>
        </div>
      `
    }

    // Generar secciones por partner
    const allPartners = new Set([
      ...Object.keys(opportunitiesByPartner.new || {}),
      ...Object.keys(opportunitiesByPartner.existing || {}),
      ...Object.keys(opportunitiesByPartner.won || {}),
      ...Object.keys(opportunitiesByPartner.inactive || {}),
    ])

    // Ordenar partners: primero los que tienen nombre, luego "Sin Partner"
    const sortedPartners = Array.from(allPartners).sort((a, b) => {
      if (a === "Sin Partner") return 1
      if (b === "Sin Partner") return -1
      return a.localeCompare(b)
    })

    const partnerSections = sortedPartners
      .map((partnerName) => {
        const partnerData = {
          new: opportunitiesByPartner.new[partnerName] || [],
          existing: opportunitiesByPartner.existing[partnerName] || [],
          won: opportunitiesByPartner.won[partnerName] || [],
          inactive: opportunitiesByPartner.inactive[partnerName] || [],
        }
        return generatePartnerSection(partnerName, partnerData)
      })
      .join("")

    return `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
        <!-- Header RESPONSIVE: Horizontal en Desktop, Vertical en Mobile -->
        <div style="background: linear-gradient(135deg, ${scaleupBlue} 0%, #003d82 100%); color: white; padding: 30px 20px; border-radius: 15px; box-shadow: 0 6px 12px rgba(0,0,0,0.15); position: relative;">
          <!-- Desktop Layout (Horizontal) -->
          <div style="display: flex; align-items: center; justify-content: space-between;" class="desktop-header">
            <!-- Logo ScaleUp (izquierda) -->
            <div style="flex: 0 0 auto; margin-right: 30px;">
              <img src="/images/design-mode/scaleup-logo-white.png" alt="ScaleUp" style="height: 45px; object-fit: contain;">
            </div>
            
            <!-- Contenido central -->
            <div style="flex: 1; text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center;">
              <h1 style="margin: 0; font-size: 28px; font-weight: 700; line-height: 1.2; color: white;">📊 ${t.weeklyReport}</h1>
              <br>
              <p style="margin: 0; opacity: 0.85; font-size: 15px; line-height: 1.2; color: white; display: block;">${t.generatedOn} ${formattedDate}</p>
            </div>
            
            <!-- Logo Tech Company (derecha) -->
            <div style="flex: 0 0 auto; margin-left: 30px;">
              ${
                techCompany.logo_url
                  ? `<img src="${techCompany.logo_url}" alt="${techCompany.name}" style="height: 45px; width: auto; max-width: 120px; object-fit: contain; background-color: white; padding: 8px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">`
                  : `<div style="width: 45px; height: 45px; background-color: rgba(255,255,255,0.2); border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 20px;">🏢</div>`
              }
            </div>
          </div>
          
          <!-- Mobile Layout (Vertical) - Hidden by default, shown on mobile -->
          <div style="display: none; text-align: center;" class="mobile-header">
            <!-- Logo ScaleUp centrado arriba -->
            <div style="margin-bottom: 20px;">
              <img src="/images/design-mode/scaleup-logo-white.png" alt="ScaleUp" style="height: 40px; object-fit: contain;">
            </div>
            
            <!-- Título centrado -->
            <div style="margin-bottom: 20px;">
              <div style="margin: 0; font-size: 24px; font-weight: 700; line-height: 1.1; color: white;">📊 ${t.weeklyReport}</div>
              <br>
              <div style="margin: 0; opacity: 0.85; font-size: 14px; line-height: 1.1; color: white;">${t.generatedOn} ${formattedDate}</div>
            </div>
            
            <!-- Logo Tech Company centrado abajo -->
            <div>
              ${
                techCompany.logo_url
                  ? `<img src="${techCompany.logo_url}" alt="${techCompany.name}" style="height: 40px; width: auto; max-width: 200px; object-fit: contain; background-color: white; padding: 8px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">`
                  : `<div style="width: 40px; height: 40px; background-color: rgba(255,255,255,0.2); border-radius: 8px; display: inline-flex; align-items: center; justify-content: center; font-size: 20px;">🏢</div>`
              }
            </div>
          </div>
          
          <!-- Media Query para Mobile -->
          <style>
            @media only screen and (max-width: 768px) {
              .desktop-header { display: none !important; }
              .mobile-header { display: block !important; }
            }
          </style>
        </div>
        
        <!-- Resumen Ejecutivo -->
        <div style="background: white; padding: 15px; border-radius: 10px; margin-top: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border: 1px solid #e9ecef;">
          <!-- Título muy pequeño -->
          <h2 style="color: ${scaleupBlue}; margin: 0 0 10px 0; font-size: 16px; font-weight: 700; text-align: center;">📈 ${t.summary}</h2>
          
          <!-- Tabla compacta de KPIs -->
          <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
            <tr>
              <td style="padding: 8px; text-align: center; background: linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%); border: 1px solid #90caf9; border-radius: 6px; margin: 2px;">
                <div style="font-size: 18px; font-weight: 800; color: ${scaleupBlue}; line-height: 1;">${summary.totalActiveOpportunities}</div>
                <div style="font-size: 8px; color: #1565c0; font-weight: 600; text-transform: uppercase;">${t.active}</div>
                <div style="font-size: 9px; color: #1976d2; font-weight: 600;">${formatCurrency(summary.totalActiveValue)}</div>
              </td>
              <td style="width: 5px;"></td>
              <td style="padding: 8px; text-align: center; background: linear-gradient(135deg, #e8f5e8 0%, #c8e6c9 100%); border: 1px solid #81c784; border-radius: 6px; margin: 2px;">
                <div style="font-size: 18px; font-weight: 800; color: #28a745; line-height: 1;">${summary.newThisWeek}</div>
                <div style="font-size: 8px; color: #2e7d32; font-weight: 600; text-transform: uppercase;">${t.new}</div>
                <div style="font-size: 9px; color: #388e3c; font-weight: 600;">${formatCurrency(summary.totalNewValue)}</div>
              </td>
              <td style="width: 5px;"></td>
              <td style="padding: 8px; text-align: center; background: linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%); border: 1px solid #ffb74d; border-radius: 6px; margin: 2px;">
                <div style="font-size: 18px; font-weight: 800; color: #f57c00; line-height: 1;">${summary.wonThisWeek}</div>
                <div style="font-size: 8px; color: #ef6c00; font-weight: 600; text-transform: uppercase;">${t.won}</div>
                <div style="font-size: 9px; color: #f57c00; font-weight: 600;">${formatCurrency(summary.totalWonValue)}</div>
              </td>
              <td style="width: 5px;"></td>
              <td style="padding: 8px; text-align: center; background: linear-gradient(135deg, #ffebee 0%, #ffcdd2 100%); border: 1px solid #e57373; border-radius: 6px; margin: 2px;">
                <div style="font-size: 18px; font-weight: 800; color: #dc3545; line-height: 1;">${summary.inactiveThisWeek}</div>
                <div style="font-size: 8px; color: #c62828; font-weight: 600; text-transform: uppercase;">${t.lost}</div>
                <div style="font-size: 7px; color: #d32f2f; font-weight: 500;">${t.thisWeek}</div>
              </td>
            </tr>
          </table>
          
          <!-- Actividad en una línea muy pequeña -->
          <div style="margin-top: 8px; display: flex; gap: 5px; font-size: 10px;">
            <div style="flex: 1; background: #e8f5e8; padding: 6px; border-radius: 4px; text-align: center; border: 1px solid #c8e6c9;">
              <span style="font-size: 14px; font-weight: 700; color: #28a745;">${summary.withActivity}</span>
              <span style="font-size: 8px; color: #2e7d32; font-weight: 600; margin-left: 3px;">${t.withActivity}</span>
            </div>
            <div style="flex: 1; background: #ffebee; padding: 6px; border-radius: 4px; text-align: center; border: 1px solid #ffcdd2;">
              <span style="font-size: 14px; font-weight: 700; color: #dc3545;">${summary.withoutActivity}</span>
              <span style="font-size: 8px; color: #c62828; font-weight: 600; margin-left: 3px;">${t.withoutActivity}</span>
            </div>
          </div>
        </div>

        <!-- Leyenda de colores -->
        <div style="background: white; padding: 10px; border-radius: 8px; margin-top: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border: 1px solid #e9ecef;">
          <div style="font-size: 11px; color: #666; text-align: center;">
            <strong>${t.estimatedClose}:</strong> 
            <span style="background: #ffebee; padding: 2px 6px; border-radius: 3px; margin: 0 4px;">🔴 ${t.overdue}</span>
            <span style="background: #fff8e1; padding: 2px 6px; border-radius: 3px; margin: 0 4px;">🟡 ${t.dueIn7Days}</span>
          </div>
        </div>

        <!-- Secciones por Partner -->
        <div style="margin-top: 25px;">
          <div style="text-align: center; margin-bottom: 25px;">
            <h2 style="color: ${scaleupBlue}; font-size: 22px; margin: 0; font-weight: 700; display: flex; align-items: center; justify-content: center;">
              <span style="font-size: 26px; margin-right: 10px;">🤝</span>
              ${t.opportunitiesByPartner}
            </h2>
            <div style="width: 60px; height: 3px; background: linear-gradient(90deg, ${scaleupBlue}, #007bff); margin: 12px auto; border-radius: 2px;"></div>
          </div>
          ${partnerSections}
        </div>

        <!-- Footer -->
        <div style="margin-top: 30px; padding: 20px; background: linear-gradient(135deg, #ffffff 0%, #f8f9fa 100%); border-radius: 12px; text-align: center; border-top: 3px solid ${scaleupBlue}; box-shadow: 0 3px 6px rgba(0,0,0,0.1);">
          <p style="margin: 0; font-size: 12px; color: #666; line-height: 1.5;">
            ${t.autoGenerated} <strong style="color: ${scaleupBlue};">ScaleUp CRM</strong> ${t.generatedOn.toLowerCase()} ${formattedDate}.<br>
            <strong>${t.lastActivity}:</strong> ${t.activityNote}<br>
            <strong>Nota:</strong> ${t.frozenLostNote}
          </p>
        </div>
      </div>
    `
  }

  static async sendAllWeeklyReports() {
    console.log(`[WeeklyReportServiceV8] === INICIO sendAllWeeklyReports ===`)

    try {
      const supabase = createServerClient()

      // Obtener todas las tech companies que tienen configuración de reportes
      const { data: techCompanies, error } = await supabase
        .from("weekly_report_recipients")
        .select(`
          tech_company_id,
          tech_companies (
            id,
            name
          )
        `)
        .eq("is_active", true)

      console.log(`[WeeklyReportServiceV8] Query result:`, { 
        data: techCompanies, 
        error,
        dataLength: techCompanies?.length 
      })

      if (error) {
        console.error(`[WeeklyReportServiceV8] Error getting tech companies:`, error)
        return { success: false, error: error.message }
      }

      if (!techCompanies || techCompanies.length === 0) {
        console.log(`[WeeklyReportServiceV8] No tech companies with active recipients found`)
        console.log(`[WeeklyReportServiceV8] Attempting to check raw table count...`)
        
        // Debug: intentar contar directamente sin joins
        const { count, error: countError } = await supabase
          .from("weekly_report_recipients")
          .select("*", { count: "exact", head: true })
          .eq("is_active", true)

        console.log(`[WeeklyReportServiceV8] Raw count:`, { count, countError })

        return { success: true, results: [], message: "No tech companies configured" }
      }

      // Obtener IDs únicos de tech companies
      const uniqueTechCompanyIds = Array.from(new Set(techCompanies.map((tc) => tc.tech_company_id)))

      console.log(`[WeeklyReportServiceV8] Found ${uniqueTechCompanyIds.length} tech companies to process`)

      const allResults = []

      // Procesar cada tech company
      for (const techCompanyId of uniqueTechCompanyIds) {
        console.log(`[WeeklyReportServiceV8] Processing tech company: ${techCompanyId}`)

        try {
          const result = await this.sendWeeklyReport(techCompanyId, supabase)
          allResults.push({
            techCompanyId,
            ...result,
          })
        } catch (error) {
          console.error(`[WeeklyReportServiceV8] Error processing ${techCompanyId}:`, error)
          allResults.push({
            techCompanyId,
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
          })
        }
      }

      console.log(`[WeeklyReportServiceV8] === FIN sendAllWeeklyReports ===`)

      return {
        success: true,
        results: allResults,
        summary: {
          totalTechCompanies: uniqueTechCompanyIds.length,
          successful: allResults.filter((r) => r.success).length,
          failed: allResults.filter((r) => !r.success).length,
        },
      }
    } catch (error) {
      console.error(`[WeeklyReportServiceV8] Error general:`, error)
      return {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      }
    }
  }
}
