export const DICT_LANG_PROSPECT_PARTNERS = {
  es: {
    "prospect_partners.page.title": "Partners Potenciales",
    "prospect_partners.page.description": "Gestiona los partners potenciales de tu negocio",
    "prospect_partners.create": "Nuevo Partner Potencial",
    "prospect_partners.search.title": "Buscar Partners",
    "prospect_partners.search": "Buscar por nombre, código o website...",
    "prospect_partners.filter.all": "Todos",
    "prospect_partners.filter.clear": "Limpiar filtros",
    "prospect_partners.filter.status": "Estado",
    "prospect_partners.filter.leadSource": "Fuente de Lead",
    "prospect_partners.refresh": "Actualizar",
    "prospect_partners.title": "Partners Potenciales",
    "prospect_partners.showing": "Mostrando",
    "prospect_partners.of": "de",
    "prospect_partners.pagination.page": "Página",
    "prospect_partners.pagination.of": "de",
    "prospect_partners.pagination.previous": "Anterior",
    "prospect_partners.pagination.next": "Siguiente",
    "prospect_partners.name": "Nombre",
    "prospect_partners.code": "Código",
    "prospect_partners.website": "Sitio Web",
    "prospect_partners.country": "País",
    "prospect_partners.leadSource": "Fuente de Lead",
    "prospect_partners.convertedAt": "Convertido en",
    "prospect_partners.status": "Estado",
    "prospect_partners.status.active": "Activo",
    "prospect_partners.status.inactive": "Inactivo",
    "prospect_partners.actions": "Acciones",
    "prospect_partners.edit": "Editar",
    "prospect_partners.delete": "Eliminar",
    "prospect_partners.view": "Ver",
    "prospect_partners.confirm.delete": "¿Estás seguro que deseas eliminar este partner?",
    "prospect_partners.message.loading": "Cargando partners...",
    "prospect_partners.message.noContacts": "Sin contactos asociados",
    "prospect_partners.message.noOpportunities": "Sin oportunidades asociadas",
    "prospect_partners.drawer.title": "Detalles del Partner",
    "prospect_partners.drawer.generalInfo": "Información General",
    "prospect_partners.drawer.contacts": "Contactos Asociados",
    "prospect_partners.drawer.opportunities": "Oportunidades",
    "prospect_partners.drawer.addContact": "Agregar Contacto",
    "prospect_partners.form.title": "Nuevo Partner Potencial",
    "prospect_partners.form.edit": "Editar Partner Potencial",
    "prospect_partners.form.name": "Nombre *",
    "prospect_partners.form.code": "Código",
    "prospect_partners.form.website": "Sitio Web",
    "prospect_partners.form.country": "País",
    "prospect_partners.form.address": "Dirección",
    "prospect_partners.form.leadSource": "Fuente de Lead",
    "prospect_partners.form.save": "Guardar",
    "prospect_partners.form.cancel": "Cancelar",
    "prospect_partners.form.success": "Partner guardado exitosamente",
    "prospect_partners.form.error": "Error al guardar el partner",
    "prospect_partners.contact.add": "Agregar Contacto",
    "prospect_partners.contact.firstName": "Nombre *",
    "prospect_partners.contact.lastName": "Apellido *",
    "prospect_partners.contact.email": "Email *",
    "prospect_partners.contact.phone": "Teléfono",
    "prospect_partners.contact.position": "Cargo",
    "prospect_partners.contact.department": "Departamento",
    "prospect_partners.contact.save": "Guardar Contacto",
    "prospect_partners.contact.cancel": "Cancelar",
    "prospect_partners.contact.success": "Contacto agregado exitosamente",
    "prospect_partners.contact.error": "Error al agregar el contacto",
  },
  en: {
    "prospect_partners.page.title": "Potential Partners",
    "prospect_partners.page.description": "Manage your potential business partners",
    "prospect_partners.create": "New Potential Partner",
    "prospect_partners.search.title": "Search Partners",
    "prospect_partners.search": "Search by name, code or website...",
    "prospect_partners.filter.all": "All",
    "prospect_partners.filter.clear": "Clear filters",
    "prospect_partners.filter.status": "Status",
    "prospect_partners.filter.leadSource": "Lead Source",
    "prospect_partners.refresh": "Refresh",
    "prospect_partners.title": "Potential Partners",
    "prospect_partners.showing": "Showing",
    "prospect_partners.of": "of",
    "prospect_partners.pagination.page": "Page",
    "prospect_partners.pagination.of": "of",
    "prospect_partners.pagination.previous": "Previous",
    "prospect_partners.pagination.next": "Next",
    "prospect_partners.name": "Name",
    "prospect_partners.code": "Code",
    "prospect_partners.website": "Website",
    "prospect_partners.country": "Country",
    "prospect_partners.leadSource": "Lead Source",
    "prospect_partners.convertedAt": "Converted At",
    "prospect_partners.status": "Status",
    "prospect_partners.status.active": "Active",
    "prospect_partners.status.inactive": "Inactive",
    "prospect_partners.actions": "Actions",
    "prospect_partners.edit": "Edit",
    "prospect_partners.delete": "Delete",
    "prospect_partners.view": "View",
    "prospect_partners.confirm.delete": "Are you sure you want to delete this partner?",
    "prospect_partners.message.loading": "Loading partners...",
    "prospect_partners.message.noContacts": "No associated contacts",
    "prospect_partners.message.noOpportunities": "No associated opportunities",
    "prospect_partners.drawer.title": "Partner Details",
    "prospect_partners.drawer.generalInfo": "General Information",
    "prospect_partners.drawer.contacts": "Associated Contacts",
    "prospect_partners.drawer.opportunities": "Opportunities",
    "prospect_partners.drawer.addContact": "Add Contact",
    "prospect_partners.form.title": "New Potential Partner",
    "prospect_partners.form.edit": "Edit Potential Partner",
    "prospect_partners.form.name": "Name *",
    "prospect_partners.form.code": "Code",
    "prospect_partners.form.website": "Website",
    "prospect_partners.form.country": "Country",
    "prospect_partners.form.address": "Address",
    "prospect_partners.form.leadSource": "Lead Source",
    "prospect_partners.form.save": "Save",
    "prospect_partners.form.cancel": "Cancel",
    "prospect_partners.form.success": "Partner saved successfully",
    "prospect_partners.form.error": "Error saving partner",
    "prospect_partners.contact.add": "Add Contact",
    "prospect_partners.contact.firstName": "First Name *",
    "prospect_partners.contact.lastName": "Last Name *",
    "prospect_partners.contact.email": "Email *",
    "prospect_partners.contact.phone": "Phone",
    "prospect_partners.contact.position": "Position",
    "prospect_partners.contact.department": "Department",
    "prospect_partners.contact.save": "Save Contact",
    "prospect_partners.contact.cancel": "Cancel",
    "prospect_partners.contact.success": "Contact added successfully",
    "prospect_partners.contact.error": "Error adding contact",
  },
  pt: {
    "prospect_partners.page.title": "Parceiros Potenciais",
    "prospect_partners.page.description": "Gerencie seus potenciais parceiros de negócios",
    "prospect_partners.create": "Novo Parceiro Potencial",
    "prospect_partners.search.title": "Pesquisar Parceiros",
    "prospect_partners.search": "Pesquisar por nome, código ou site...",
    "prospect_partners.filter.all": "Todos",
    "prospect_partners.filter.clear": "Limpar filtros",
    "prospect_partners.filter.status": "Status",
    "prospect_partners.filter.leadSource": "Fonte de Lead",
    "prospect_partners.refresh": "Atualizar",
    "prospect_partners.title": "Parceiros Potenciais",
    "prospect_partners.showing": "Mostrando",
    "prospect_partners.of": "de",
    "prospect_partners.pagination.page": "Página",
    "prospect_partners.pagination.of": "de",
    "prospect_partners.pagination.previous": "Anterior",
    "prospect_partners.pagination.next": "Próximo",
    "prospect_partners.name": "Nome",
    "prospect_partners.code": "Código",
    "prospect_partners.website": "Site",
    "prospect_partners.country": "País",
    "prospect_partners.leadSource": "Fonte de Lead",
    "prospect_partners.convertedAt": "Convertido em",
    "prospect_partners.status": "Status",
    "prospect_partners.status.active": "Ativo",
    "prospect_partners.status.inactive": "Inativo",
    "prospect_partners.actions": "Ações",
    "prospect_partners.edit": "Editar",
    "prospect_partners.delete": "Deletar",
    "prospect_partners.view": "Visualizar",
    "prospect_partners.confirm.delete": "Tem certeza que deseja deletar este parceiro?",
    "prospect_partners.message.loading": "Carregando parceiros...",
    "prospect_partners.message.noContacts": "Sem contatos associados",
    "prospect_partners.message.noOpportunities": "Sem oportunidades associadas",
    "prospect_partners.drawer.title": "Detalhes do Parceiro",
    "prospect_partners.drawer.generalInfo": "Informações Gerais",
    "prospect_partners.drawer.contacts": "Contatos Associados",
    "prospect_partners.drawer.opportunities": "Oportunidades",
    "prospect_partners.drawer.addContact": "Adicionar Contato",
    "prospect_partners.form.title": "Novo Parceiro Potencial",
    "prospect_partners.form.edit": "Editar Parceiro Potencial",
    "prospect_partners.form.name": "Nome *",
    "prospect_partners.form.code": "Código",
    "prospect_partners.form.website": "Site",
    "prospect_partners.form.country": "País",
    "prospect_partners.form.address": "Endereço",
    "prospect_partners.form.leadSource": "Fonte de Lead",
    "prospect_partners.form.save": "Salvar",
    "prospect_partners.form.cancel": "Cancelar",
    "prospect_partners.form.success": "Parceiro salvo com sucesso",
    "prospect_partners.form.error": "Erro ao salvar o parceiro",
    "prospect_partners.contact.add": "Adicionar Contato",
    "prospect_partners.contact.firstName": "Primeiro Nome *",
    "prospect_partners.contact.lastName": "Sobrenome *",
    "prospect_partners.contact.email": "Email *",
    "prospect_partners.contact.phone": "Telefone",
    "prospect_partners.contact.position": "Posição",
    "prospect_partners.contact.department": "Departamento",
    "prospect_partners.contact.save": "Salvar Contato",
    "prospect_partners.contact.cancel": "Cancelar",
    "prospect_partners.contact.success": "Contato adicionado com sucesso",
    "prospect_partners.contact.error": "Erro ao adicionar o contato",
  },
}
