export function PortugueseTermsContent() {
  return (
    <>
      <h3 className="text-lg font-semibold">Termos e Condições de Uso</h3>
      <p>Última atualização: 30 de agosto de 2026</p>
      <div className="mt-4 flex flex-col gap-4">
        <section><h4 className="font-medium">1. Introdução</h4><p>Bem-vindo ao ScaleUp CRM. Estes Termos e Condições regem o uso da nossa plataforma e serviços. Ao acessar ou usar o ScaleUp CRM, você concorda em cumprir estes Termos.</p></section>
        <section><h4 className="font-medium">2. Definições</h4><p>“Plataforma” refere-se ao software, site e serviços do ScaleUp CRM.</p><p>“Usuário”, “Você” ou “Seu” refere-se à pessoa física ou jurídica que acessa ou usa a Plataforma.</p><p>“Nós”, “Nos” ou “Nosso” refere-se à ScaleUp, empresa proprietária e operadora da Plataforma.</p></section>
        <section><h4 className="font-medium">3. Registro de Conta</h4><p>Para utilizar determinados recursos da Plataforma, você deve se registrar para obter uma conta. Você concorda em fornecer informações precisas, atuais e completas durante o processo de registro.</p><p>Você é responsável por manter a confidencialidade das credenciais da sua conta e por todas as atividades que ocorrerem sob sua conta.</p></section>
        <section><h4 className="font-medium">4. Uso da Plataforma</h4><p>Você concorda em utilizar a Plataforma apenas para fins lícitos e de acordo com estes Termos.</p><p>Você concorda em não utilizar a Plataforma:</p><ul className="list-disc pl-6"><li>De qualquer maneira que viole qualquer lei ou regulamento aplicável.</li><li>Para transmitir qualquer material difamatório, ofensivo ou de outra forma censurável.</li><li>Para tentar interferir no funcionamento adequado da Plataforma.</li><li>Para tentar obter acesso não autorizado a qualquer parte da Plataforma.</li></ul></section>
        <section><h4 className="font-medium">5. Privacidade de Dados</h4><p>A ScaleUp está comprometida em proteger a privacidade dos usuários da Plataforma. Ao utilizar nossos serviços, você concorda com a coleta e o processamento de certos dados pessoais necessários para o funcionamento do CRM, incluindo dados de contato, atividade dentro da Plataforma e arquivos enviados.</p><p>As informações serão utilizadas exclusivamente para fins operacionais e comerciais relacionados ao uso da Plataforma, e não serão compartilhadas com terceiros sem o seu consentimento, exceto por obrigação legal.</p></section>
        <section><h4 className="font-medium">6. Propriedade Intelectual</h4><p>A Plataforma e seu conteúdo original, recursos e funcionalidades são de propriedade da ScaleUp e estão protegidos por leis internacionais de direitos autorais, marcas registradas, patentes, segredos comerciais e outras leis de propriedade intelectual.</p></section>
        <section><h4 className="font-medium">7. Uso da Imagem Comercial e Marcas Registradas</h4><p>Ao se registrar e utilizar a Plataforma, Você concede à ScaleUp uma licença não exclusiva, gratuita e de alcance mundial para utilizar o nome comercial, logotipo e marca(s) da sua empresa exclusivamente para fins de marketing, promoção e divulgação em nossas redes sociais, site e outros canais oficiais de comunicação da ScaleUp.</p><p>Caso não deseje que utilizemos sua marca ou logotipo em nosso material promocional, você poderá nos notificar a qualquer momento enviando um e-mail para support@scaleup-global.com, e procederemos com a remoção de tais informações em um prazo razoável.</p></section>
        <section><h4 className="font-medium">8. Rescisão</h4><p>Podemos encerrar ou suspender sua conta e o acesso à Plataforma imediatamente, sem aviso prévio ou responsabilidade, por qualquer motivo, incluindo, sem limitação, se você descumprir estes Termos.</p></section>
        <section><h4 className="font-medium">9. Limitação de Responsabilidade</h4><p>Em nenhum caso a ScaleUp, nem seus diretores, funcionários, parceiros, agentes, fornecedores ou afiliados, serão responsáveis por quaisquer danos indiretos, incidentais, especiais, consequenciais ou punitivos, incluindo, sem limitação, perda de lucros, dados, uso, fundo de comércio ou outras perdas intangíveis, resultantes do seu acesso ou uso, ou da incapacidade de acessar ou usar a Plataforma.</p></section>
        <section><h4 className="font-medium">10. Alterações nos Termos</h4><p>Reservamo-nos o direito de modificar ou substituir estes Termos a qualquer momento. Se uma revisão for material, forneceremos um aviso com pelo menos 30 dias de antecedência antes que os novos termos entrem em vigor.</p></section>
        <section><h4 className="font-medium">11. Entre em Contato</h4><p>Se você tiver alguma dúvida sobre estes Termos, entre em contato conosco pelo e-mail support@scaleup-global.com.</p></section>
      </div>
    </>
  )
}
