export function EnglishTermsContent() {
  return (
    <>
      <h3 className="text-lg font-semibold">Terms and Conditions of Use</h3>
      <p>Last updated: August 30, 2026</p>
      <div className="mt-4 flex flex-col gap-4">
        <section><h4 className="font-medium">1. Introduction</h4><p>Welcome to ScaleUp CRM. These Terms and Conditions govern your use of our platform and services. By accessing or using ScaleUp CRM, you agree to be bound by these Terms.</p></section>
        <section><h4 className="font-medium">2. Definitions</h4><p>“Platform” refers to ScaleUp CRM software, website, and services.</p><p>“User”, “You”, or “Your” refers to the individual or entity accessing or using the Platform.</p><p>“We”, “Us”, or “Our” refers to ScaleUp, the owner and operator of the Platform.</p></section>
        <section><h4 className="font-medium">3. Account Registration</h4><p>To use certain features of the Platform, you must register for an account. You agree to provide accurate, current, and complete information during the registration process.</p><p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p></section>
        <section><h4 className="font-medium">4. Use of the Platform</h4><p>You agree to use the Platform only for lawful purposes and in accordance with these Terms.</p><p>You agree not to use the Platform:</p><ul className="list-disc pl-6"><li>In any way that violates any applicable law or regulation.</li><li>To transmit any material that is defamatory, offensive, or otherwise objectionable.</li><li>To attempt to interfere with the proper functioning of the Platform.</li><li>To attempt to gain unauthorized access to any part of the Platform.</li></ul></section>
        <section><h4 className="font-medium">5. Data Privacy</h4><p>ScaleUp is committed to protecting the privacy of Platform users. By using our services, you agree to our collection and processing of certain personal data necessary for the CRM&apos;s operation, including contact details, in-platform activity, and uploaded files.</p><p>This information will be used exclusively for operational and commercial purposes related to the use of the Platform, and will not be shared with third parties without your consent, except where required by law.</p></section>
        <section><h4 className="font-medium">6. Intellectual Property</h4><p>The Platform and its original content, features, and functionality are the property of ScaleUp and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.</p></section>
        <section><h4 className="font-medium">7. Use of Commercial Image and Trademarks</h4><p>By registering and using the Platform, You grant ScaleUp a non-exclusive, royalty-free, worldwide license to use your company&apos;s trade name, logo, and trademark(s) solely for marketing, promotion, and public relations purposes across ScaleUp&apos;s social media channels, website, and other official communication channels.</p><p>If you do not wish for us to use your trademark or logo in our promotional materials, you may opt out at any time by sending an email to support@scaleup-global.com, and we will proceed to remove such assets within a reasonable timeframe.</p></section>
        <section><h4 className="font-medium">8. Termination</h4><p>We may terminate or suspend your account and access to the Platform immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms.</p></section>
        <section><h4 className="font-medium">9. Limitation of Liability</h4><p>In no event shall ScaleUp, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Platform.</p></section>
        <section><h4 className="font-medium">10. Changes to Terms</h4><p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days&apos; notice prior to any new terms taking effect.</p></section>
        <section><h4 className="font-medium">11. Contact Us</h4><p>If you have any questions about these Terms, please contact us at support@scaleup-global.com.</p></section>
      </div>
    </>
  )
}
