-- Traducciones para reportes semanales de tech companies

-- Función para insertar traducciones
CREATE OR REPLACE FUNCTION insert_weekly_translation(p_key TEXT, p_en TEXT, p_es TEXT, p_pt TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO translations (key, language, value)
  VALUES (p_key, 'en', p_en)
  ON CONFLICT (key, language) 
  DO UPDATE SET value = p_en;
  
  INSERT INTO translations (key, language, value)
  VALUES (p_key, 'es', p_es)
  ON CONFLICT (key, language) 
  DO UPDATE SET value = p_es;
  
  INSERT INTO translations (key, language, value)
  VALUES (p_key, 'pt', p_pt)
  ON CONFLICT (key, language) 
  DO UPDATE SET value = p_pt;
END;
$$ LANGUAGE plpgsql;

-- Título y encabezados principales
SELECT insert_weekly_translation(
  'weekly_report.title', 
  'Weekly Opportunities Report', 
  'Reporte Semanal de Oportunidades', 
  'Relatório Semanal de Oportunidades'
);

SELECT insert_weekly_translation(
  'weekly_report.subtitle', 
  'Summary of opportunities and activities for', 
  'Resumen de oportunidades y actividades para', 
  'Resumo de oportunidades e atividades para'
);

SELECT insert_weekly_translation(
  'weekly_report.period', 
  'Period', 
  'Período', 
  'Período'
);

-- Sección de resumen
SELECT insert_weekly_translation(
  'weekly_report.summary.title', 
  'Executive Summary', 
  'Resumen Ejecutivo', 
  'Resumo Executivo'
);

SELECT insert_weekly_translation(
  'weekly_report.summary.open_opportunities', 
  'Open Opportunities', 
  'Oportunidades Abiertas', 
  'Oportunidades Abertas'
);

SELECT insert_weekly_translation(
  'weekly_report.summary.with_activity', 
  'With activity this week', 
  'Con actividad esta semana', 
  'Com atividade esta semana'
);

SELECT insert_weekly_translation(
  'weekly_report.summary.without_activity', 
  'Without activity this week', 
  'Sin actividad esta semana', 
  'Sem atividade esta semana'
);

SELECT insert_weekly_translation(
  'weekly_report.summary.closed_this_week', 
  'Opportunities closed this week', 
  'Oportunidades cerradas esta semana', 
  'Oportunidades fechadas esta semana'
);

SELECT insert_weekly_translation(
  'weekly_report.summary.comparison', 
  'vs. previous week', 
  'vs. semana anterior', 
  'vs. semana anterior'
);

-- Estados de oportunidades
SELECT insert_weekly_translation(
  'weekly_report.status.new', 
  'New Opportunities', 
  'Oportunidades Nuevas', 
  'Oportunidades Novas'
);

SELECT insert_weekly_translation(
  'weekly_report.status.existing', 
  'Existing Opportunities', 
  'Oportunidades Existentes', 
  'Oportunidades Existentes'
);

SELECT insert_weekly_translation(
  'weekly_report.status.closed_won', 
  'Closed Won', 
  'Cerradas Ganadas', 
  'Fechadas Ganhas'
);

SELECT insert_weekly_translation(
  'weekly_report.status.closed_lost', 
  'Closed Lost', 
  'Cerradas Perdidas', 
  'Fechadas Perdidas'
);

-- Columnas de la tabla
SELECT insert_weekly_translation(
  'weekly_report.table.country', 
  'Country', 
  'País', 
  'País'
);

SELECT insert_weekly_translation(
  'weekly_report.table.opportunity_name', 
  'Opportunity Name', 
  'Nombre de Oportunidad', 
  'Nome da Oportunidade'
);

SELECT insert_weekly_translation(
  'weekly_report.table.amount', 
  'Amount', 
  'Monto', 
  'Valor'
);

SELECT insert_weekly_translation(
  'weekly_report.table.estimated_close', 
  'Estimated Close Date', 
  'Fecha Estimada de Cierre', 
  'Data Estimada de Fechamento'
);

SELECT insert_weekly_translation(
  'weekly_report.table.partner', 
  'Partner', 
  'Partner', 
  'Parceiro'
);

SELECT insert_weekly_translation(
  'weekly_report.table.stage', 
  'Stage', 
  'Etapa', 
  'Estágio'
);

-- Mensajes generales
SELECT insert_weekly_translation(
  'weekly_report.no_opportunities', 
  'No opportunities found for this period', 
  'No se encontraron oportunidades para este período', 
  'Nenhuma oportunidade encontrada para este período'
);

SELECT insert_weekly_translation(
  'weekly_report.footer', 
  'This is an automated weekly report generated by ScaleUp CRM. Do not reply to this email.', 
  'Este es un reporte semanal automático generado por ScaleUp CRM. No responder a este email.', 
  'Este é um relatório semanal automático gerado pelo ScaleUp CRM. Não responda a este email.'
);

-- Configuración de reportes
SELECT insert_weekly_translation(
  'weekly_report.config.title', 
  'Weekly Report Configuration', 
  'Configuración de Reportes Semanales', 
  'Configuração de Relatórios Semanais'
);

SELECT insert_weekly_translation(
  'weekly_report.config.description', 
  'Configure who receives weekly reports for each tech company', 
  'Configura quién recibe reportes semanales para cada empresa tecnológica', 
  'Configure quem recebe relatórios semanais para cada empresa tecnológica'
);

SELECT insert_weekly_translation(
  'weekly_report.config.tech_company', 
  'Tech Company', 
  'Empresa Tecnológica', 
  'Empresa Tecnológica'
);

SELECT insert_weekly_translation(
  'weekly_report.config.recipients', 
  'Recipients', 
  'Destinatarios', 
  'Destinatários'
);

SELECT insert_weekly_translation(
  'weekly_report.config.add_recipient', 
  'Add Recipient', 
  'Agregar Destinatario', 
  'Adicionar Destinatário'
);

SELECT insert_weekly_translation(
  'weekly_report.config.remove_recipient', 
  'Remove', 
  'Eliminar', 
  'Remover'
);

SELECT insert_weekly_translation(
  'weekly_report.config.save_changes', 
  'Save Changes', 
  'Guardar Cambios', 
  'Salvar Alterações'
);

SELECT insert_weekly_translation(
  'weekly_report.config.send_test', 
  'Send Test Report', 
  'Enviar Reporte de Prueba', 
  'Enviar Relatório de Teste'
);

-- Limpiar función temporal
DROP FUNCTION insert_weekly_translation(TEXT, TEXT, TEXT, TEXT);
