"use client"

import { Fragment, useEffect, useState, type KeyboardEvent } from "react"
import Image from "next/image"
import { Mail, Send, X } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { useAuth } from "@/components/auth/auth-provider"
import { useTranslations } from "@/hooks/use-translations"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { toast } from "sonner"

type Projection = { id?: string; partner_id: string; tech_company_id: string; period_year: number; period_quarter: number | null; target_opportunities_declared: number; target_opportunities_proposal: number; target_opportunities_won: number; target_revenue_amount: number; currency: string; target_posts_published: number; target_success_cases: number; created_by_user_id?: string }
type Option = { id: string; name: string; logo_url?: string | null }
type Recipient = { email: string; label: string }
type Metric = { key: keyof Pick<Projection, "target_opportunities_declared" | "target_opportunities_proposal" | "target_opportunities_won" | "target_revenue_amount" | "target_posts_published" | "target_success_cases">; label: string; money?: boolean }

const emptyProjection = (partnerId: string, techId: string, year: number, quarter: number): Projection => ({ partner_id: partnerId, tech_company_id: techId, period_year: year, period_quarter: quarter, target_opportunities_declared: 0, target_opportunities_proposal: 0, target_opportunities_won: 0, target_revenue_amount: 0, currency: "USD", target_posts_published: 0, target_success_cases: 0 })

export function ForecastPage() {
  const supabase = createClient()
  const { userInfo } = useAuth()
  const { language } = useTranslations()
  const copy = language === "en" ? { title: "Annual Forecast", subtitle: "Load all quarters in one financial matrix.", partner: "Partner", tech: "TechCompany", year: "Year", select: "Select", metric: "Metric", commercial: "COMMERCIAL GOALS", marketing: "MARKETING GOALS", declared: "Declared opportunities", proposal: "Opportunities in proposal", won: "Won opportunities", revenue: "Estimated revenue USD", posts: "Published posts", cases: "Success cases", total: "ANNUAL TOTAL", send: "Send executive minutes by email when saving", recipients: "Recipients", team: "ScaleUP Team", external: "Add external email", save: "Save Forecast and Send Minutes", saved: "Forecast saved", noData: "Select a Partner and TechCompany to begin", loading: "Saving..." } : language === "pt" ? { title: "Forecast Anual", subtitle: "Carregue todos os trimestres em uma matriz financeira.", partner: "Partner", tech: "TechCompany", year: "Ano", select: "Selecionar", metric: "Métrica", commercial: "METAS COMERCIAIS", marketing: "METAS DE MARKETING", declared: "Oportunidades declaradas", proposal: "Oportunidades em proposta", won: "Oportunidades ganhas", revenue: "Receita estimada USD", posts: "Posts publicados", cases: "Casos de sucesso", total: "TOTAL ANUAL", send: "Enviar minuta executiva por email ao salvar", recipients: "Destinatários", team: "Equipe ScaleUP", external: "Adicionar email externo", save: "Salvar Forecast e Enviar Minuta", saved: "Forecast salvo", noData: "Selecione um Partner e uma TechCompany para começar", loading: "Salvando..." } : { title: "Forecast Anual", subtitle: "Cargá todos los quarters en una matriz financiera.", partner: "Partner", tech: "TechCompany", year: "Año", select: "Seleccionar", metric: "Métrica", commercial: "METAS COMERCIALES", marketing: "METAS DE MARKETING", declared: "Oportunidades declaradas", proposal: "Oportunidades en propuesta", won: "Oportunidades ganadas", revenue: "Revenue estimado USD", posts: "Posts publicados", cases: "Casos de éxito", total: "TOTAL ANUAL", send: "Enviar minuta ejecutiva por email al guardar", recipients: "Destinatarios", team: "Equipo ScaleUP", external: "Agregar email externo", save: "Guardar Forecast y Enviar Minuta", saved: "Forecast guardado", noData: "Seleccioná un Partner y una TechCompany para comenzar", loading: "Guardando..." }
  const [partners, setPartners] = useState<Option[]>([]), [allPartners, setAllPartners] = useState<Option[]>([]), [techCompanies, setTechCompanies] = useState<Option[]>([]), [partnerId, setPartnerId] = useState(""), [techId, setTechId] = useState(""), [year, setYear] = useState("2026"), [rows, setRows] = useState<Projection[]>([]), [loading, setLoading] = useState(false), [sendEmail, setSendEmail] = useState(true), [recipientInput, setRecipientInput] = useState(""), [recipients, setRecipients] = useState<Recipient[]>([])
  const metrics: { group: "commercial" | "marketing"; items: Metric[] }[] = [{ group: "commercial", items: [{ key: "target_opportunities_declared", label: copy.declared }, { key: "target_opportunities_proposal", label: copy.proposal }, { key: "target_opportunities_won", label: copy.won }, { key: "target_revenue_amount", label: copy.revenue, money: true }] }, { group: "marketing", items: [{ key: "target_posts_published", label: copy.posts }, { key: "target_success_cases", label: copy.cases }] }]

  useEffect(() => { void (async () => { const isBdd = userInfo?.roleCode?.toLowerCase() === "bdd"; let relationQuery = supabase.from("partner_tech_companies").select("partner_id, tech_company_id"); if (isBdd && userInfo?.id) relationQuery = relationQuery.eq("scaleup_manager_id", userInfo.id); const [{ data: relations }, { data: allTechCompanies }] = await Promise.all([relationQuery, supabase.from("tech_companies").select("id,name,logo_url").order("name")]); const relationRows = relations || []; const managedTechIds = new Set(relationRows.map((item: { tech_company_id: string }) => item.tech_company_id)); const managedPartnerIds = new Set(relationRows.map((item: { partner_id: string }) => item.partner_id)); const techRows = isBdd ? (allTechCompanies || []).filter((item) => managedTechIds.has(item.id)) : (allTechCompanies || []); const { data: partnerRows } = await supabase.from("partners").select("id,name,logo_url").order("name"); setTechCompanies(techRows); setAllPartners(isBdd ? (partnerRows || []).filter((item) => managedPartnerIds.has(item.id)) : (partnerRows || [])); setPartners(isBdd ? (partnerRows || []).filter((item) => managedPartnerIds.has(item.id)) : (partnerRows || [])); })() }, [userInfo?.id, userInfo?.roleCode])
  useEffect(() => { if (!techId) { setPartnerId(""); return }; void (async () => { const { data: relations } = await supabase.from("partner_tech_companies").select("partner_id").eq("tech_company_id", techId); const ids = new Set((relations || []).map((item: { partner_id: string }) => item.partner_id)); const filteredPartners = allPartners.filter((item) => ids.has(item.id)); setPartners(filteredPartners); setPartnerId((current) => filteredPartners.some((item) => item.id === current) ? current : ""); })() }, [techId, allPartners])
  useEffect(() => { if (!partnerId || !techId) { setRows([]); return }; void (async () => { setLoading(true); const { data } = await (supabase.from("partner_tech_projections" as any).select("*") as any).eq("partner_id", partnerId).eq("tech_company_id", techId).eq("period_year", Number(year)); setRows([1, 2, 3, 4].map((q) => data?.find((item: Projection) => item.period_quarter === q) || emptyProjection(partnerId, techId, Number(year), q))); setLoading(false) })() }, [partnerId, techId, year])
  const update = (quarter: number, key: Metric["key"], value: string) => setRows((current) => current.map((row) => row.period_quarter === quarter ? { ...row, [key]: Number(value) } : row))
  const annualTotal = (key: Metric["key"]) => rows.reduce((sum, row) => sum + Number(row[key] || 0), 0)
  const addExternal = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === "Enter" && recipientInput.trim()) { event.preventDefault(); setRecipients((current) => [...current, { email: recipientInput.trim(), label: recipientInput.trim() }]); setRecipientInput("") } }
  const save = async () => { if (!partnerId || !techId || !userInfo?.id) return; setLoading(true); const payload = rows.map((row) => ({ ...row, created_by_user_id: userInfo.id })); const { error } = await (supabase.from("partner_tech_projections" as any) as any).upsert(payload, { onConflict: "partner_id,tech_company_id,period_year,period_quarter" }); setLoading(false); if (error) { toast.error(error.message); return }; toast.success(copy.saved); if (sendEmail && recipients.length) await fetch("/api/forecasts/send-minutes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipients: recipients.map((item) => item.email), projections: payload, partner: partners.find((item) => item.id === partnerId)?.name, techCompany: techCompanies.find((item) => item.id === techId)?.name }) }) }
  const selectedPartner = partners.find((item) => item.id === partnerId)?.name, selectedTech = techCompanies.find((item) => item.id === techId)?.name
  const suggestedRecipients: Recipient[] = [{ email: "ceo@scaleup.com", label: "CEO" }, { email: "bdd@scaleup.com", label: "BDD" }]
  const toggleRecipient = (recipient: Recipient) => setRecipients((current) => current.some((item) => item.email === recipient.email) ? current.filter((item) => item.email !== recipient.email) : [...current, recipient])

  return <main className="min-h-screen bg-muted/20 p-6"><div className="mx-auto flex max-w-7xl flex-col gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">ScaleUP CRM / Forecast</p><h1 className="text-3xl font-semibold tracking-tight text-balance">{copy.title} {selectedPartner && selectedTech ? `${Number(year)} — ${selectedPartner} × ${selectedTech}` : Number(year)}</h1><p className="mt-1 text-muted-foreground">{copy.subtitle}</p></div><Button onClick={save} disabled={!partnerId || !techId || loading}><Send data-icon="inline-start" />{loading ? copy.loading : copy.save}</Button></header>
    <Card><CardContent className="grid gap-4 p-4 md:grid-cols-3"><div><Label>{copy.tech}</Label><Select value={techId} onValueChange={setTechId}><SelectTrigger className="mt-2"><SelectValue placeholder={copy.select} /></SelectTrigger><SelectContent>{techCompanies.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.partner}</Label><Select value={partnerId} onValueChange={setPartnerId} disabled={!techId}><SelectTrigger className="mt-2"><SelectValue placeholder={techId ? copy.select : copy.tech} /></SelectTrigger><SelectContent>{partners.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.year}</Label><Select value={year} onValueChange={setYear}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{[2026, 2027, 2028].map((item) => <SelectItem key={item} value={String(item)}>{item}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
    {!partnerId || !techId ? <Card><CardContent className="flex min-h-64 items-center justify-center text-muted-foreground">{copy.noData}</CardContent></Card> : <Card className="overflow-hidden"><CardHeader className="border-b"><CardTitle className="flex items-center gap-3 text-lg"><span className="flex items-center gap-2">{partners.find((item) => item.id === partnerId)?.logo_url ? <Image src={partners.find((item) => item.id === partnerId)?.logo_url || ""} alt={`Logo de ${selectedPartner}`} width={40} height={40} className="size-10 rounded-md border object-contain" /> : <span className="flex size-10 items-center justify-center rounded-md border bg-muted text-xs font-semibold">P</span>}{selectedPartner}</span><span className="text-muted-foreground">×</span><span className="flex items-center gap-2">{techCompanies.find((item) => item.id === techId)?.logo_url ? <Image src={techCompanies.find((item) => item.id === techId)?.logo_url || ""} alt={`Logo de ${selectedTech}`} width={40} height={40} className="size-10 rounded-md border object-contain" /> : <span className="flex size-10 items-center justify-center rounded-md border bg-muted text-xs font-semibold">T</span>}{selectedTech}</span><span className="text-muted-foreground">· {Number(year)}</span></CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] border-collapse"><thead><tr className="border-b bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><th className="p-4 text-left font-medium">{copy.metric}</th>{[1, 2, 3, 4].map((q) => <th key={q} className="w-32 p-4 text-right font-medium">Q{q}</th>)}<th className="w-36 bg-primary/5 p-4 text-right font-semibold text-primary">{copy.total}</th></tr></thead><tbody>{metrics.map(({ group, items }) => <Fragment key={group}><tr className="border-b bg-muted/20"><th colSpan={6} className="px-4 py-3 text-left text-xs font-semibold tracking-widest text-primary">{group === "commercial" ? copy.commercial : copy.marketing}</th></tr>{items.map((metric) => <tr key={metric.key} className={`border-b ${group === "marketing" ? "bg-muted/10" : "bg-background"}`}><th className="whitespace-nowrap px-4 py-2 text-left text-sm font-medium">{metric.label}</th>{[1, 2, 3, 4].map((q) => <td key={q} className="p-2"><div className="relative"><Input aria-label={`${metric.label} Q${q}`} className="h-9 text-right tabular-nums" type="number" min="0" value={rows.find((row) => row.period_quarter === q)?.[metric.key] ?? 0} onChange={(event) => update(q, metric.key, event.target.value)} />{metric.money && <span className="pointer-events-none absolute left-2 top-2 text-xs text-muted-foreground">$</span>}</div></td>)}<td className="bg-primary/5 px-4 text-right text-sm font-bold tabular-nums text-primary">{metric.money ? `$${annualTotal(metric.key).toLocaleString()}` : annualTotal(metric.key).toLocaleString()}</td></tr>)}</Fragment>)}</tbody></table></CardContent></Card>}
    {partnerId && techId && <Card className="bg-muted/30"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Mail data-icon="inline-start" />{copy.send}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex items-center gap-3"><Checkbox id="send-minutes" checked={sendEmail} onCheckedChange={(checked) => setSendEmail(checked === true)} /><Label htmlFor="send-minutes">{copy.send}</Label></div><Separator /><div className="flex flex-wrap gap-2"><span className="w-full text-xs font-medium text-muted-foreground">{copy.team}</span>{suggestedRecipients.map((recipient) => <button type="button" key={recipient.email} aria-pressed={recipients.some((item) => item.email === recipient.email)} onClick={() => toggleRecipient(recipient)} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm transition-colors hover:bg-muted"><Checkbox checked={recipients.some((item) => item.email === recipient.email)} tabIndex={-1} />{recipient.label}<span className="text-xs text-muted-foreground">{recipient.email}</span></button>)}</div><div><Label htmlFor="external-email">{copy.external}</Label><Input id="external-email" className="mt-2 max-w-md" value={recipientInput} onChange={(event) => setRecipientInput(event.target.value)} onKeyDown={addExternal} placeholder="email@domain.com" /></div><div className="flex flex-wrap gap-2">{recipients.filter((item) => !suggestedRecipients.some((suggested) => suggested.email === item.email)).map((recipient) => <Badge key={recipient.email} variant="secondary">{recipient.email}<button type="button" className="ml-1" onClick={() => toggleRecipient(recipient)} aria-label="Remove"><X data-icon="inline-end" /></button></Badge>)}</div></CardContent></Card>}
  </div></main>
}
