"use client"

import { useEffect, useMemo, useState } from "react"
import { CalendarDays, Check, Mail, Megaphone, Pencil, Plus, Save, Target, Trophy, Users } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { useAuth } from "@/components/auth/auth-provider"
import { useTranslations } from "@/hooks/use-translations"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Separator } from "@/components/ui/separator"
import { toast } from "sonner"

type Projection = { id?: string; partner_id: string; tech_company_id: string; period_year: number; period_quarter: number | null; target_opportunities_declared: number; target_opportunities_proposal: number; target_opportunities_won: number; target_revenue_amount: number; currency: string; target_posts_published: number; target_success_cases: number; created_by_user_id?: string; created_at?: string }
type Option = { id: string; name: string }

const emptyProjection = (partner_id: string, tech_company_id: string, year: number, quarter: number | null): Projection => ({ partner_id, tech_company_id, period_year: year, period_quarter: quarter, target_opportunities_declared: 0, target_opportunities_proposal: 0, target_opportunities_won: 0, target_revenue_amount: 0, currency: "USD", target_posts_published: 0, target_success_cases: 0 })

export function ForecastPage() {
  const supabase = createClient()
  const { userInfo } = useAuth()
  const { language } = useTranslations()
  const isAdmin = Boolean(userInfo?.isAdmin || userInfo?.roleCode?.toLowerCase() === "admin")
  const copy = language === "en" ? { title: "Forecast & Annual Projections", partner: "Partner", tech: "TechCompany", year: "Year", period: "Period", annual: "Annual", load: "Load agreed forecast", save: "Save forecast", edit: "Edit forecast", commercial: "Commercial goals", marketing: "Marketing goals", declared: "Declared opportunities", proposal: "Opportunities in proposal", won: "Won opportunities", revenue: "Estimated revenue", posts: "Published posts", cases: "Success cases", author: "Loaded by", send: "Send executive minutes by email", recipients: "Recipients", noData: "Select a Partner and TechCompany to begin", saved: "Forecast saved" } : language === "pt" ? { title: "Forecast e Projeções Anuais", partner: "Partner", tech: "TechCompany", year: "Ano", period: "Período", annual: "Anual", load: "Carregar forecast acordado", save: "Salvar forecast", edit: "Editar forecast", commercial: "Metas comerciais", marketing: "Metas de marketing", declared: "Oportunidades declaradas", proposal: "Oportunidades em proposta", won: "Oportunidades ganhas", revenue: "Receita estimada", posts: "Posts publicados", cases: "Casos de sucesso", author: "Carregado por", send: "Enviar minuta executiva por email", recipients: "Destinatários", noData: "Selecione um Partner e uma TechCompany para começar", saved: "Forecast salvo" } : { title: "Forecast y Proyecciones Anuales", partner: "Partner", tech: "TechCompany", year: "Año", period: "Período", annual: "Anual", load: "Cargar Forecast Acordado", save: "Guardar Forecast", edit: "Editar Forecast", commercial: "Metas comerciales", marketing: "Metas de marketing", declared: "Oportunidades declaradas", proposal: "Oportunidades en propuesta", won: "Oportunidades ganadas", revenue: "Revenue estimado", posts: "Posts publicados", cases: "Casos de éxito", author: "Cargado por", send: "Enviar minuta ejecutiva por email", recipients: "Destinatarios", noData: "Seleccioná un Partner y una TechCompany para comenzar", saved: "Forecast guardado" }
  const [partners, setPartners] = useState<Option[]>([]), [techCompanies, setTechCompanies] = useState<Option[]>([]), [partnerId, setPartnerId] = useState(""), [techId, setTechId] = useState(""), [year, setYear] = useState("2026"), [quarter, setQuarter] = useState("annual"), [projection, setProjection] = useState<Projection | null>(null), [loading, setLoading] = useState(false), [editing, setEditing] = useState(false), [sendEmail, setSendEmail] = useState(true), [recipients, setRecipients] = useState("")
  const periodQuarter = quarter === "annual" ? null : Number(quarter)

  useEffect(() => { void (async () => { const [{ data: p }, { data: t }] = await Promise.all([supabase.from("partners").select("id,name").order("name"), supabase.from("tech_companies").select("id,name").order("name")]); setPartners(p || []); setTechCompanies(t || []) })() }, [])
  useEffect(() => { if (!partnerId || !techId) { setProjection(null); return }; void (async () => { setLoading(true); let query = (supabase.from("partner_tech_projections" as any).select("*") as any).eq("partner_id", partnerId).eq("tech_company_id", techId).eq("period_year", Number(year)); query = periodQuarter === null ? query.is("period_quarter", null) : query.eq("period_quarter", periodQuarter); const { data } = await query.maybeSingle(); setProjection(data || null); setEditing(!data); setLoading(false) })() }, [partnerId, techId, year, quarter])
  const active = projection || (partnerId && techId ? emptyProjection(partnerId, techId, Number(year), periodQuarter) : null)
  const update = (key: keyof Projection, value: string) => setProjection((current) => ({ ...(current || emptyProjection(partnerId, techId, Number(year), periodQuarter)), [key]: Number(value) }))
  const save = async () => { if (!active || !userInfo?.id) return; setLoading(true); const payload = { ...active, created_by_user_id: userInfo.id }; const { data, error } = await (supabase.from("partner_tech_projections" as any) as any).upsert(payload, { onConflict: "partner_id,tech_company_id,period_year,period_quarter" }).select().single(); setLoading(false); if (error) { toast.error(error.message); return }; setProjection(data); setEditing(false); toast.success(copy.saved); if (sendEmail && recipients.trim()) await fetch("/api/forecasts/send-minutes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipients: recipients.split(",").map((email) => email.trim()).filter(Boolean), projection: data, partner: partners.find((p) => p.id === partnerId)?.name, techCompany: techCompanies.find((t) => t.id === techId)?.name }) }) }
  const fields = useMemo(() => [["target_opportunities_declared", copy.declared], ["target_opportunities_proposal", copy.proposal], ["target_opportunities_won", copy.won], ["target_revenue_amount", copy.revenue]] as const, [copy])
  return <main className="min-h-screen bg-muted/20 p-6"><div className="mx-auto flex max-w-7xl flex-col gap-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-primary">ScaleUP CRM</p><h1 className="text-3xl font-semibold tracking-tight">{copy.title}</h1><p className="mt-1 text-muted-foreground">Acordá objetivos comerciales y de marketing con cada Partner.</p></div><Button onClick={() => setEditing(true)} disabled={!active}><Plus data-icon="inline-start" />{copy.load}</Button></div>
    <Card><CardContent className="grid gap-4 p-4 md:grid-cols-4"><div><Label>{copy.partner}</Label><Select value={partnerId} onValueChange={setPartnerId}><SelectTrigger className="mt-2"><SelectValue placeholder={copy.partner} /></SelectTrigger><SelectContent>{partners.filter((p) => isAdmin || true).map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.tech}</Label><Select value={techId} onValueChange={setTechId}><SelectTrigger className="mt-2"><SelectValue placeholder={copy.tech} /></SelectTrigger><SelectContent>{techCompanies.map((t) => <SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.year}</Label><Select value={year} onValueChange={setYear}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2026">2026</SelectItem><SelectItem value="2027">2027</SelectItem></SelectContent></Select></div><div><Label>{copy.period}</Label><Select value={quarter} onValueChange={setQuarter}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="annual">{copy.annual}</SelectItem>{[1,2,3,4].map((q) => <SelectItem key={q} value={String(q)}>Q{q}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
    {!active ? <Card><CardContent className="flex min-h-56 items-center justify-center text-muted-foreground">{copy.noData}</CardContent></Card> : <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{partners.find((p) => p.id === partnerId)?.name} × {techCompanies.find((t) => t.id === techId)?.name}</CardTitle>{projection && <Badge variant="secondary"><Check data-icon="inline-start" />{copy.author}: {projection.created_by_user_id?.slice(0, 8)}</Badge>}</CardHeader><CardContent className="flex flex-col gap-6"><section><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><Target className="size-5 text-primary" />{copy.commercial}</h2><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <div key={key}><Label>{label}</Label><Input className="mt-2" type="number" min="0" value={active[key] ?? 0} disabled={!editing} onChange={(e) => update(key, e.target.value)} /></div>)}</div></section><Separator /><section className="rounded-xl bg-muted/50 p-4"><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><Megaphone className="size-5 text-primary" />{copy.marketing}</h2><div className="grid gap-4 sm:grid-cols-2"><div><Label>{copy.posts}</Label><Input className="mt-2" type="number" min="0" value={active.target_posts_published} disabled={!editing} onChange={(e) => update("target_posts_published", e.target.value)} /></div><div><Label>{copy.cases}</Label><Input className="mt-2" type="number" min="0" value={active.target_success_cases} disabled={!editing} onChange={(e) => update("target_success_cases", e.target.value)} /></div></div></section>{editing && <div className="flex justify-end"><Button onClick={save} disabled={loading}><Save data-icon="inline-start" />{copy.save}</Button></div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Mail className="size-5 text-primary" />{copy.send}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex items-center gap-2"><Checkbox checked={sendEmail} onCheckedChange={(v) => setSendEmail(Boolean(v))} id="send-minutes" /><Label htmlFor="send-minutes">{copy.send}</Label></div><Label htmlFor="recipients">{copy.recipients}</Label><Input id="recipients" placeholder="email1@empresa.com, email2@empresa.com" value={recipients} onChange={(e) => setRecipients(e.target.value)} /><p className="text-xs text-muted-foreground">Separá los emails con comas.</p></CardContent></Card></div>}
  </div></main>
}
